Circle 2.0
q-centrix/health-data-standards pull request #34
Opened 2018-08-24 22:42 UTC by bradlamotte

https://qcentrix.atlassian.net/browse/ACS-762

Had to install MongoDB in the primary container instead of using a separate service container in order to get MongoDB v2.6 because v3 is the lowest the service containers go.  This is because using v3 was throwing this error:
```
Mongo::Error::OperationFailure: Mongo::Error::OperationFailure: The 'cursor' option is required, except for aggregate with the explain argument (9)
```
I also added test reporting so the summary is displayed atop Circle.

2018-08-27 18:22 UTC, dillonwelch requested changes

2018-08-27 18:22 UTC, dillonwelch commented on .circleci/config.yml
> +            - vendor/bundle
`./vendor/bundle`

2018-08-27 18:22 UTC, dillonwelch commented on .circleci/config.yml
> +      - run: bundle install --without staging doc
`--jobs=4`

2018-08-27 18:22 UTC, dillonwelch commented on Gemfile
> +  gem 'minitest-ci'
What's this for?

2018-08-27 18:22 UTC, dillonwelch commented on lib/tasks/hqmf.rake
> +
As annoying as it is to leave it, revert the spaces cleanup to this file because it will make merging in the latest code even more of a PITA.

2018-08-27 19:01 UTC, bradlamotte commented on Gemfile
> +  gem 'minitest-ci'
To allow minitest results to be uploaded to Circle

2018-08-27 19:10 UTC, oniofchaos commented on Gemfile
> +  gem 'minitest-ci'
Can you add a comment for that

2018-08-27 19:38 UTC, bradlamotte commented on Gemfile
> +  gem 'minitest-ci'
In the Gemfile?

2018-08-27 19:39 UTC, oniofchaos commented on Gemfile
> +  gem 'minitest-ci'
`gem 'minitest-ci' # needed to upload test results on circle 2.0`

2018-08-28 19:16 UTC, merged

2018-08-28 19:27 UTC, oniofchaos commented
The branch failed after I merged this in, can you check it out